# Generated by Django 5.1.1 on 2024-10-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomsmall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='submission_date',
            field=models.DateField(null=True),
        ),
    ]
