# Generated by Django 5.1.1 on 2024-10-23 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomsmall', '0002_alter_studentassignment_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentdetails', to='classroomsmall.student'),
        ),
    ]
