# Generated by Django 5.1.1 on 2024-10-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomsmall', '0006_wellnessresource_visited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessresource',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
