# Generated by Django 5.1.1 on 2024-11-01 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomsmall', '0007_wellnessresource_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiteboard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='whiteboard',
            name='drawing_data',
            field=models.TextField(blank=True),
        ),
    ]
