# Generated by Django 5.1.1 on 2024-11-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomsmall', '0008_whiteboard_created_at_whiteboard_drawing_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
