# Generated by Django 5.1.1 on 2024-11-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomsmall', '0009_teacher_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(default='pending', upload_to='assignments/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
