# Generated by Django 5.1.1 on 2024-11-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomsmall', '0010_assignment_assignment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
