# Generated by Django 5.1.1 on 2024-11-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomsmall', '0011_alter_studentassignment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='submission_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Graded', 'Graded')], default='Pending', max_length=9),
        ),
    ]
